### ISSUE TITLE
Password for wm8880 linuz firmware?

### ISSUE THREAD

**Issue by MKBandzz** [keensam04/aakash_bazaar_client#4]

**Comment by MKBandzz** [comment]
Hi i am in canada i have a wm8880 i wanted linux on it so i put it on my sd card. I asks me for a password to "student" do you know what it is? I cant use linux without it.

**Comment by srikantpatnaik** [comment]
All passwords are "student" (without quotes).

**Comment by MKBandzz** [comment]
Ok thanks!
